version: "3"
services:
  mongo:
    image: mongo:3
    ports:
      - 27017:27017
    environment:
      MONGO_DATA_DIR: /data/db
    volumes:
      - ./data/db:/data/db
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
#      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: example